# Generated by Django 4.0 on 2022-03-25 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Avatars')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(choices=[('T1', 'MODULO DOMOTICO'), ('T2', 'MODULO SENSOR TEMPERATURA'), ('T3', 'MODULO IMPRESORA 3D'), ('T4', 'ESP32 - 4'), ('T5', 'ESP32 - 5'), ('T6', 'ESP32 - 6'), ('T7', 'ESP32 - 7'), ('T8', 'ESP32 - 8'), ('T9', 'ESP32 - 9'), ('T10', 'ESP32 -10')], default='ESP32 - 1', max_length=15)),
                ('archivo', models.FileField(upload_to='Archivos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin'])])),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
