# Generated by Django 4.0 on 2022-01-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
