# Generated by Django 4.0 on 2022-02-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='usuarios',
        ),
    ]
