# Generated by Django 4.0 on 2022-01-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_archivo_fecha_remove_archivo_tamaño_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
