# Generated by Django 4.0 on 2022-02-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_archivo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='user',
            new_name='username',
        ),
    ]
