# Generated by Django 4.0 on 2022-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='estado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
