# Generated by Django 4.0 on 2022-01-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='tarjeta',
        ),
    ]
