# Generated by Django 4.0 on 2022-02-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_rename_user_archivo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='username',
        ),
    ]
