# Generated by Django 4.0 on 2022-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_archivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tarjeta',
            field=models.CharField(choices=[('T1', 'MODULO DOMOTICO'), ('T2', 'MODULO SENSOR TEMPERATURA'), ('T3', 'MODULO IMPRESORA 3D')], default='ESP32 - 1', max_length=15),
        ),
    ]
