# Generated by Django 4.0 on 2022-01-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_remove_archivo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='tarjeta',
            field=models.CharField(choices=[('T1', 'ESP32 - 1'), ('T2', 'ESP32 - 2'), ('T3', 'ESP32 - 3'), ('T4', 'ESP32 - 4'), ('T5', 'ESP32 - 5'), ('T6', 'ESP32 - 6'), ('T7', 'ESP32 - 7'), ('T8', 'ESP32 - 8'), ('T9', 'ESP32 - 9'), ('T10', 'ESP32 -10')], default='ESP32 - 1', max_length=15),
        ),
    ]
