# Generated by Django 4.0 on 2022-06-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_archivo_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='estado',
        ),
    ]
