# Generated by Django 4.0 on 2022-01-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_archivo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
