# Generated by Django 4.0 on 2022-02-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('upload', '0008_alter_archivo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
