# Generated by Django 4.0 on 2022-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_alter_archivo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
