# Generated by Django 4.0 on 2022-02-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_archivo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='user',
        ),
    ]
