# Generated by Django 4.0 on 2022-02-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('upload', '0010_remove_archivo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
