# Generated by Django 4.0 on 2022-06-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_alter_archivo_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='tarjeta',
        ),
        migrations.AddField(
            model_name='archivo',
            name='t1',
            field=models.CharField(default='MODULO DOMOTICO', max_length=30),
        ),
        migrations.AddField(
            model_name='archivo',
            name='t2',
            field=models.CharField(default='MODULO TEMPERATURA', max_length=30),
        ),
        migrations.AddField(
            model_name='archivo',
            name='t3',
            field=models.CharField(default='MODULO MOTOR ELECTRICO', max_length=30),
        ),
        migrations.AddField(
            model_name='archivo',
            name='t4',
            field=models.CharField(default='MODULO INCUBADORA', max_length=30),
        ),
    ]
