# Generated by Django 4.0 on 2022-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_remove_archivo_tarjeta_archivo_t1_archivo_t2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='t4',
        ),
        migrations.AddField(
            model_name='archivo',
            name='tarjeta',
            field=models.CharField(choices=[('T1', 'MODULO DOMOTICO'), ('T2', 'MODULO SENSOR TEMPERATURA'), ('T3', 'MODULO MOTOR ELECTRICO'), ('T4', 'MODULO INCUBADORA')], default='MODULO DOMOTICO', max_length=15),
        ),
    ]
