# Generated by Django 4.0 on 2022-07-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_remove_archivo_t1_remove_archivo_t2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tarjeta',
            field=models.CharField(choices=[('T1', 'MODULO DOMOTICO'), ('T2', 'MODULO SENSOR TEMPERATURA'), ('T3', 'MODULO MOTOR ELECTRICO'), ('T4', 'MODULO INCUBADORA')], max_length=15),
        ),
    ]
