# Generated by Django 4.0 on 2022-02-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('upload', '0013_alter_archivo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
