# Generated by Django 4.0 on 2022-02-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_alter_archivo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='usuario',
        ),
    ]
