# Generated by Django 4.0 on 2022-07-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tarjeta',
            field=models.CharField(blank=True, choices=[('T1', 'MODULO DOMOTICO'), ('T2', 'MODULO SENSOR TEMPERATURA'), ('T3', 'MODULO MOTOR ELECTRICO'), ('T4', 'MODULO INCUBADORA')], max_length=15),
        ),
    ]
